/* This file is generated by etc/ffgen.c during build do not edit */
#ifndef GAP_FFDATA_H
#define GAP_FFDATA_H

#include "common.h"

enum {
    NUM_SHORT_FINITE_FIELDS = 6635,
    MAXSIZE_GF_INTERNAL = 65536,
    DEGREE_LARGEST_INTERNAL_FF = 16,
    FIELD_BITS_FFE = 13,
    VAL_BITS_FFE = 16
};

extern const UInt4 SizeFF[NUM_SHORT_FINITE_FIELDS+1];
extern const UInt1 DegrFF[NUM_SHORT_FINITE_FIELDS+1];
extern const UInt4 CharFF[NUM_SHORT_FINITE_FIELDS+1];


#endif // GAP_FFDATA_H
